
set_property PACKAGE_PIN BF41 [get_ports prst_n]
set_property PULLUP true [get_ports prst_n]
set_property IOSTANDARD LVCMOS12 [get_ports prst_n]
set_false_path -from [get_ports prst_n]

set_property PACKAGE_PIN AR14 [get_ports sys_clk_n]
set_property PACKAGE_PIN AR15 [get_ports sys_clk_p]

create_clock -name sys_clk -period 10 [get_ports sys_clk_p]

set_property PACKAGE_PIN BK44 [get_ports HBM_ref_clk_n]
set_property PACKAGE_PIN BK43 [get_ports HBM_ref_clk_p]
set_property IOSTANDARD LVDS [get_ports HBM_ref_clk_n]
set_property IOSTANDARD LVDS [get_ports HBM_ref_clk_p]
create_clock -name HBM_ref_clk -period 10 [get_ports HBM_ref_clk_p]

set_false_path -from [get_clocks -of_objects [get_pins PCIE_HBM_SUB_SYS_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins PCIE_HBM_SUB_SYS_i/xdma_0/inst/pcie4c_ip_i/inst/PCIE_HBM_SUB_SYS_xdma_0_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_userclk/O]]

set_false_path -from [get_clocks -of_objects [get_pins PCIE_HBM_SUB_SYS_i/xdma_0/inst/pcie4c_ip_i/inst/PCIE_HBM_SUB_SYS_xdma_0_0_pcie4c_ip_gt_top_i/diablo_gt.diablo_gt_phy_wrapper/phy_clk_i/bufg_gt_userclk/O]] -to [get_clocks -of_objects [get_pins PCIE_HBM_SUB_SYS_i/clk_wiz_0/inst/mmcme4_adv_inst/CLKOUT0]]

set_property PACKAGE_PIN AL1 [get_ports {pcie_rxn[0]}]
set_property PACKAGE_PIN AM3 [get_ports {pcie_rxn[1]}]
set_property PACKAGE_PIN AN5 [get_ports {pcie_rxn[2]}]
set_property PACKAGE_PIN AN1 [get_ports {pcie_rxn[3]}]
set_property PACKAGE_PIN AP3 [get_ports {pcie_rxn[4]}]
set_property PACKAGE_PIN AR1 [get_ports {pcie_rxn[5]}]
set_property PACKAGE_PIN AT3 [get_ports {pcie_rxn[6]}]
set_property PACKAGE_PIN AU1 [get_ports {pcie_rxn[7]}]
set_property PACKAGE_PIN AL2 [get_ports {pcie_rxp[0]}]
set_property PACKAGE_PIN AM4 [get_ports {pcie_rxp[1]}]
set_property PACKAGE_PIN AN6 [get_ports {pcie_rxp[2]}]
set_property PACKAGE_PIN AN2 [get_ports {pcie_rxp[3]}]
set_property PACKAGE_PIN AP4 [get_ports {pcie_rxp[4]}]
set_property PACKAGE_PIN AR2 [get_ports {pcie_rxp[5]}]
set_property PACKAGE_PIN AT4 [get_ports {pcie_rxp[6]}]
set_property PACKAGE_PIN AU2 [get_ports {pcie_rxp[7]}]
set_property PACKAGE_PIN AL10 [get_ports {pcie_txn[0]}]
set_property PACKAGE_PIN AM8 [get_ports {pcie_txn[1]}]
set_property PACKAGE_PIN AN10 [get_ports {pcie_txn[2]}]
set_property PACKAGE_PIN AP8 [get_ports {pcie_txn[3]}]
set_property PACKAGE_PIN AR10 [get_ports {pcie_txn[4]}]
set_property PACKAGE_PIN AR6 [get_ports {pcie_txn[5]}]
set_property PACKAGE_PIN AT8 [get_ports {pcie_txn[6]}]
set_property PACKAGE_PIN AU10 [get_ports {pcie_txn[7]}]
set_property PACKAGE_PIN AL11 [get_ports {pcie_txp[0]}]
set_property PACKAGE_PIN AM9 [get_ports {pcie_txp[1]}]
set_property PACKAGE_PIN AN11 [get_ports {pcie_txp[2]}]
set_property PACKAGE_PIN AP9 [get_ports {pcie_txp[3]}]
set_property PACKAGE_PIN AR11 [get_ports {pcie_txp[4]}]
set_property PACKAGE_PIN AR7 [get_ports {pcie_txp[5]}]
set_property PACKAGE_PIN AT9 [get_ports {pcie_txp[6]}]
set_property PACKAGE_PIN AU11 [get_ports {pcie_txp[7]}]
